# Audio Model Parameters
audio:
  # Whisper supports 16kHz by default
  SAMPLE_RATE: 16000
  # Number of audio channels (1 for mono, 2 for stereo)
  CHANNELS: 1
  # Recording duration in seconds
  DURATION: 5
  # Max recording time in seconds
  EXCEED_TIME: 20
  # Silence threshold (lower is more sensitive)
  THRESHOLD: 2000
  # Duration of silence to end recording, in seconds
  SILENCE_DURATION: 5
  # Enable audio recording
  AUDIO_RECORD_ENABLE: false
  # Path to save the recorded audio file
  AUDIO_FILE_PATH: "./tmp_audio.wav"

# TTS Speaker Parameters
tts:
  # Enable TTS speaker
  TTS_SPEAK_ENABLE: false
  # Random seed for TTS
  TTS_RAMDOM_SEED: 1924
  # Path to save the TTS output audio file
  TTS_OUTPUT_FILE: "./tts_audio.wav"

# Cloud Server Infos
model:
  # Model name for the cloud server
  MODEL_SELECT: "/workspace/model/BAAI/RoboBrain2.0-7B"
  # Number of retries for planning
  MODEL_RETRY_PLANNING: 5
  MODEL_DICT:
      # Model name for the cloud server
      CLOUD_MODEL: "/workspace/model/BAAI/RoboBrain2.0-7B"
      # Deploy for the cloud server
      CLOUD_TYPE: "default"
      # API key for the cloud server
      CLOUD_API_KEY: "EMPTY"
      # URL of the cloud server
      CLOUD_SERVER: "http://localhost:4567/v1/"
      # Maximum number of chat messages to keep in memory
      MAX_CHAT_MESSAGE: 50


# Collaborator Parameters
collaborator:
  # Hostname or IP address of the server
  HOST: "127.0.0.1"
  # Port number of the server
  PORT: 6379
  # database number
  DB: 0
  # Whether clear the database on startup
  CLEAR: true
  # Password for server
  PASSWORD: ""


# Logging Parameters
logger:
  # Name of the master logger
  MASTER_LOGGER_NAME: "GlobalAgent"
  # Log level for task logger
  MASTER_LOGGER_LEVEL: "DEBUG"
  # Path to save the task log file
  MASTER_LOGGER_FILE: ".logs/master_agent.log"
  # Path to save the robot memory file
  ROBOT_MEMORY_YAML: ".log/robot_memory.yaml"
